import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta http-equiv="refresh" content="0;URL='/posts'" />    
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This page should redirect you. If not, enable JavaScript.
        </h1>

      </main>

    </div>
  )
}
